# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createEditCollection.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateEditCollectionWindow(object):
    def setupUi(self, CreateEditCollectionWindow):
        CreateEditCollectionWindow.setObjectName("CreateEditCollectionWindow")
        CreateEditCollectionWindow.resize(521, 290)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CreateEditCollectionWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newCollectionNameLabel = QtWidgets.QLabel(CreateEditCollectionWindow)
        self.newCollectionNameLabel.setObjectName("newCollectionNameLabel")
        self.horizontalLayout_2.addWidget(self.newCollectionNameLabel)
        self.newCollectionName = QtWidgets.QLineEdit(CreateEditCollectionWindow)
        self.newCollectionName.setAlignment(QtCore.Qt.AlignCenter)
        self.newCollectionName.setObjectName("newCollectionName")
        self.horizontalLayout_2.addWidget(self.newCollectionName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.newCollectionDescriptionlabel = QtWidgets.QLabel(CreateEditCollectionWindow)
        self.newCollectionDescriptionlabel.setObjectName("newCollectionDescriptionlabel")
        self.horizontalLayout_3.addWidget(self.newCollectionDescriptionlabel)
        self.newCollectionDescription = QtWidgets.QLineEdit(CreateEditCollectionWindow)
        self.newCollectionDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.newCollectionDescription.setObjectName("newCollectionDescription")
        self.horizontalLayout_3.addWidget(self.newCollectionDescription)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.newCollectionStatusLabel = QtWidgets.QLabel(CreateEditCollectionWindow)
        self.newCollectionStatusLabel.setObjectName("newCollectionStatusLabel")
        self.horizontalLayout_4.addWidget(self.newCollectionStatusLabel)
        self.newCollectionStatus = QtWidgets.QComboBox(CreateEditCollectionWindow)
        self.newCollectionStatus.setObjectName("newCollectionStatus")
        self.newCollectionStatus.addItem("")
        self.newCollectionStatus.addItem("")
        self.horizontalLayout_4.addWidget(self.newCollectionStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.newCollectionExecLabel = QtWidgets.QLabel(CreateEditCollectionWindow)
        self.newCollectionExecLabel.setObjectName("newCollectionExecLabel")
        self.horizontalLayout_6.addWidget(self.newCollectionExecLabel)
        self.newCollectionExec = QtWidgets.QLineEdit(CreateEditCollectionWindow)
        self.newCollectionExec.setAlignment(QtCore.Qt.AlignCenter)
        self.newCollectionExec.setObjectName("newCollectionExec")
        self.horizontalLayout_6.addWidget(self.newCollectionExec)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.frame = QtWidgets.QFrame(CreateEditCollectionWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hookColumnLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hookColumnLabel.setFont(font)
        self.hookColumnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hookColumnLabel.setObjectName("hookColumnLabel")
        self.verticalLayout_3.addWidget(self.hookColumnLabel)
        self.sampleHook = QtWidgets.QCheckBox(self.frame_2)
        self.sampleHook.setObjectName("sampleHook")
        self.verticalLayout_3.addWidget(self.sampleHook)
        self.sampleHook2 = QtWidgets.QCheckBox(self.frame_2)
        self.sampleHook2.setObjectName("sampleHook2")
        self.verticalLayout_3.addWidget(self.sampleHook2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.statusColumnLabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusColumnLabel.setFont(font)
        self.statusColumnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusColumnLabel.setObjectName("statusColumnLabel")
        self.verticalLayout_5.addWidget(self.statusColumnLabel)
        self.sampleStatus = QtWidgets.QComboBox(self.frame_3)
        self.sampleStatus.setObjectName("sampleStatus")
        self.sampleStatus.addItem("")
        self.sampleStatus.addItem("")
        self.verticalLayout_5.addWidget(self.sampleStatus)
        self.sampleStatus2 = QtWidgets.QComboBox(self.frame_3)
        self.sampleStatus2.setObjectName("sampleStatus2")
        self.sampleStatus2.addItem("")
        self.sampleStatus2.addItem("")
        self.verticalLayout_5.addWidget(self.sampleStatus2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.execColumnLabel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.execColumnLabel.setFont(font)
        self.execColumnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.execColumnLabel.setObjectName("execColumnLabel")
        self.verticalLayout_7.addWidget(self.execColumnLabel)
        self.sampleExec = QtWidgets.QLineEdit(self.frame_4)
        self.sampleExec.setFrame(True)
        self.sampleExec.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleExec.setObjectName("sampleExec")
        self.verticalLayout_7.addWidget(self.sampleExec)
        self.sampleExec2 = QtWidgets.QLineEdit(self.frame_4)
        self.sampleExec2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sampleExec2.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleExec2.setObjectName("sampleExec2")
        self.verticalLayout_7.addWidget(self.sampleExec2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.newCollectionSaveButton = QtWidgets.QPushButton(CreateEditCollectionWindow)
        self.newCollectionSaveButton.setObjectName("newCollectionSaveButton")
        self.horizontalLayout_5.addWidget(self.newCollectionSaveButton)
        self.newCollectionCancelButton = QtWidgets.QPushButton(CreateEditCollectionWindow)
        self.newCollectionCancelButton.setObjectName("newCollectionCancelButton")
        self.horizontalLayout_5.addWidget(self.newCollectionCancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(CreateEditCollectionWindow)
        self.newCollectionCancelButton.clicked.connect(CreateEditCollectionWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CreateEditCollectionWindow)

    def retranslateUi(self, CreateEditCollectionWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateEditCollectionWindow.setWindowTitle(_translate("CreateEditCollectionWindow", "Create/Edit Hook Collection"))
        self.newCollectionNameLabel.setText(_translate("CreateEditCollectionWindow", "Hook Collection Name"))
        self.newCollectionName.setText(_translate("CreateEditCollectionWindow", "Hook name"))
        self.newCollectionDescriptionlabel.setText(_translate("CreateEditCollectionWindow", "Description"))
        self.newCollectionDescription.setText(_translate("CreateEditCollectionWindow", "Description"))
        self.newCollectionStatusLabel.setText(_translate("CreateEditCollectionWindow", "Status"))
        self.newCollectionStatus.setItemText(0, _translate("CreateEditCollectionWindow", "Enabled"))
        self.newCollectionStatus.setItemText(1, _translate("CreateEditCollectionWindow", "Disabled"))
        self.newCollectionExecLabel.setText(_translate("CreateEditCollectionWindow", "Execution Sequence"))
        self.newCollectionExec.setText(_translate("CreateEditCollectionWindow", "Enter Sequence no."))
        self.hookColumnLabel.setText(_translate("CreateEditCollectionWindow", "Hook"))
        self.sampleHook.setText(_translate("CreateEditCollectionWindow", "Hook1"))
        self.sampleHook2.setText(_translate("CreateEditCollectionWindow", "Hook2"))
        self.statusColumnLabel.setText(_translate("CreateEditCollectionWindow", "Status"))
        self.sampleStatus.setItemText(0, _translate("CreateEditCollectionWindow", "Enable"))
        self.sampleStatus.setItemText(1, _translate("CreateEditCollectionWindow", "Disable"))
        self.sampleStatus2.setItemText(0, _translate("CreateEditCollectionWindow", "Enable"))
        self.sampleStatus2.setItemText(1, _translate("CreateEditCollectionWindow", "Disable"))
        self.execColumnLabel.setText(_translate("CreateEditCollectionWindow", "Execution Sequence"))
        self.sampleExec.setText(_translate("CreateEditCollectionWindow", "Enter Execution Sequence no."))
        self.sampleExec2.setText(_translate("CreateEditCollectionWindow", "Enter Execution Sequence no."))
        self.newCollectionSaveButton.setText(_translate("CreateEditCollectionWindow", "Save"))
        self.newCollectionCancelButton.setText(_translate("CreateEditCollectionWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateEditCollectionWindow = QtWidgets.QDialog()
    ui = Ui_CreateEditCollectionWindow()
    ui.setupUi(CreateEditCollectionWindow)
    CreateEditCollectionWindow.show()
    sys.exit(app.exec_())

