# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcap.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pcapView(object):
    def setupUi(self, pcapView):
        pcapView.setObjectName("pcapView")
        pcapView.resize(868, 718)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        pcapView.setPalette(palette)
        self.verticalLayout = QtWidgets.QVBoxLayout(pcapView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pcapFilePanel = QtWidgets.QFrame(pcapView)
        self.pcapFilePanel.setFrameShape(QtWidgets.QFrame.Box)
        self.pcapFilePanel.setObjectName("pcapFilePanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pcapFilePanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pcapFileLabel = QtWidgets.QLabel(self.pcapFilePanel)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pcapFileLabel.setFont(font)
        self.pcapFileLabel.setObjectName("pcapFileLabel")
        self.verticalLayout_2.addWidget(self.pcapFileLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pcapFileLabel2 = QtWidgets.QLabel(self.pcapFilePanel)
        self.pcapFileLabel2.setObjectName("pcapFileLabel2")
        self.horizontalLayout.addWidget(self.pcapFileLabel2)
        self.pcapFilePath = QtWidgets.QLineEdit(self.pcapFilePanel)
        self.pcapFilePath.setObjectName("pcapFilePath")
        self.horizontalLayout.addWidget(self.pcapFilePath)
        self.pcapOpenButton = QtWidgets.QPushButton(self.pcapFilePanel)
        self.pcapOpenButton.setObjectName("pcapOpenButton")
        self.horizontalLayout.addWidget(self.pcapOpenButton)
        self.pcapCancelButton = QtWidgets.QPushButton(self.pcapFilePanel)
        self.pcapCancelButton.setObjectName("pcapCancelButton")
        self.horizontalLayout.addWidget(self.pcapCancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addWidget(self.pcapFilePanel)
        self.capFilterPanel = QtWidgets.QFrame(pcapView)
        self.capFilterPanel.setFrameShape(QtWidgets.QFrame.Box)
        self.capFilterPanel.setObjectName("capFilterPanel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.capFilterPanel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.capFilterLabel = QtWidgets.QLabel(self.capFilterPanel)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.capFilterLabel.setFont(font)
        self.capFilterLabel.setObjectName("capFilterLabel")
        self.verticalLayout_5.addWidget(self.capFilterLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.capFilterLabel2 = QtWidgets.QLabel(self.capFilterPanel)
        self.capFilterLabel2.setObjectName("capFilterLabel2")
        self.horizontalLayout_2.addWidget(self.capFilterLabel2)
        self.capFilterExpr = QtWidgets.QLineEdit(self.capFilterPanel)
        self.capFilterExpr.setObjectName("capFilterExpr")
        self.horizontalLayout_2.addWidget(self.capFilterExpr)
        self.capFilterApply = QtWidgets.QPushButton(self.capFilterPanel)
        self.capFilterApply.setObjectName("capFilterApply")
        self.horizontalLayout_2.addWidget(self.capFilterApply)
        self.capFilterClear = QtWidgets.QPushButton(self.capFilterPanel)
        self.capFilterClear.setObjectName("capFilterClear")
        self.horizontalLayout_2.addWidget(self.capFilterClear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10.addWidget(self.capFilterPanel)
        self.packetAreaPanel = QtWidgets.QFrame(pcapView)
        self.packetAreaPanel.setFrameShape(QtWidgets.QFrame.Box)
        self.packetAreaPanel.setObjectName("packetAreaPanel")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.packetAreaPanel)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.packetAreaLabel = QtWidgets.QLabel(self.packetAreaPanel)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.packetAreaLabel.setFont(font)
        self.packetAreaLabel.setObjectName("packetAreaLabel")
        self.verticalLayout_17.addWidget(self.packetAreaLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.packetDisplay = QtWidgets.QTabWidget(self.packetAreaPanel)
        self.packetDisplay.setObjectName("packetDisplay")
        self.dissectedTab = QtWidgets.QWidget()
        self.dissectedTab.setObjectName("dissectedTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dissectedTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dissectedList = QtWidgets.QTreeWidget(self.dissectedTab)
        self.dissectedList.setObjectName("dissectedList")
        item_0 = QtWidgets.QTreeWidgetItem(self.dissectedList)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.dissectedList)
        item_0 = QtWidgets.QTreeWidgetItem(self.dissectedList)
        item_0 = QtWidgets.QTreeWidgetItem(self.dissectedList)
        self.dissectedList.header().setVisible(False)
        self.verticalLayout_6.addWidget(self.dissectedList)
        self.packetDisplay.addTab(self.dissectedTab, "")
        self.binaryTab = QtWidgets.QWidget()
        self.binaryTab.setObjectName("binaryTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.binaryTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.binaryList = QtWidgets.QTreeWidget(self.binaryTab)
        self.binaryList.setObjectName("binaryList")
        self.binaryList.header().setVisible(False)
        self.verticalLayout_7.addWidget(self.binaryList)
        self.packetDisplay.addTab(self.binaryTab, "")
        self.hexTab = QtWidgets.QWidget()
        self.hexTab.setObjectName("hexTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.hexTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.hexList = QtWidgets.QTreeWidget(self.hexTab)
        self.hexList.setObjectName("hexList")
        self.hexList.headerItem().setText(0, "1")
        self.hexList.header().setVisible(False)
        self.verticalLayout_8.addWidget(self.hexList)
        self.packetDisplay.addTab(self.hexTab, "")
        self.horizontalLayout_4.addWidget(self.packetDisplay)
        self.packetClearButton = QtWidgets.QPushButton(self.packetAreaPanel)
        self.packetClearButton.setObjectName("packetClearButton")
        self.horizontalLayout_4.addWidget(self.packetClearButton, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addWidget(self.packetAreaPanel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fieldAreaPanel = QtWidgets.QFrame(pcapView)
        self.fieldAreaPanel.setFrameShape(QtWidgets.QFrame.Box)
        self.fieldAreaPanel.setObjectName("fieldAreaPanel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fieldAreaPanel)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fieldAreaLabel = QtWidgets.QLabel(self.fieldAreaPanel)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.fieldAreaLabel.setFont(font)
        self.fieldAreaLabel.setObjectName("fieldAreaLabel")
        self.verticalLayout_9.addWidget(self.fieldAreaLabel)
        self.fieldAttList = QtWidgets.QTreeWidget(self.fieldAreaPanel)
        self.fieldAttList.setMinimumSize(QtCore.QSize(475, 0))
        self.fieldAttList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fieldAttList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fieldAttList.setAllColumnsShowFocus(False)
        self.fieldAttList.setHeaderHidden(False)
        self.fieldAttList.setObjectName("fieldAttList")
        item_0 = QtWidgets.QTreeWidgetItem(self.fieldAttList)
        item_0 = QtWidgets.QTreeWidgetItem(self.fieldAttList)
        item_0 = QtWidgets.QTreeWidgetItem(self.fieldAttList)
        item_0 = QtWidgets.QTreeWidgetItem(self.fieldAttList)
        item_0 = QtWidgets.QTreeWidgetItem(self.fieldAttList)
        self.verticalLayout_9.addWidget(self.fieldAttList)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.packetSaveButton = QtWidgets.QPushButton(self.fieldAreaPanel)
        self.packetSaveButton.setObjectName("packetSaveButton")
        self.horizontalLayout_11.addWidget(self.packetSaveButton)
        self.forwardButton = QtWidgets.QPushButton(self.fieldAreaPanel)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout_11.addWidget(self.forwardButton)
        self.dropButton = QtWidgets.QPushButton(self.fieldAreaPanel)
        self.dropButton.setObjectName("dropButton")
        self.horizontalLayout_11.addWidget(self.dropButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3.addWidget(self.fieldAreaPanel)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.addToFuzzButton = QtWidgets.QPushButton(pcapView)
        self.addToFuzzButton.setMaximumSize(QtCore.QSize(30, 30))
        self.addToFuzzButton.setObjectName("addToFuzzButton")
        self.verticalLayout_16.addWidget(self.addToFuzzButton)
        self.removeFromFuzzButton = QtWidgets.QPushButton(pcapView)
        self.removeFromFuzzButton.setMaximumSize(QtCore.QSize(30, 30))
        self.removeFromFuzzButton.setObjectName("removeFromFuzzButton")
        self.verticalLayout_16.addWidget(self.removeFromFuzzButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.fuzzingAreaPanel = QtWidgets.QFrame(pcapView)
        self.fuzzingAreaPanel.setFrameShape(QtWidgets.QFrame.Box)
        self.fuzzingAreaPanel.setObjectName("fuzzingAreaPanel")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.fuzzingAreaPanel)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fuzzingAreaLabel = QtWidgets.QLabel(self.fuzzingAreaPanel)
        self.fuzzingAreaLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.fuzzingAreaLabel.setFont(font)
        self.fuzzingAreaLabel.setObjectName("fuzzingAreaLabel")
        self.verticalLayout_12.addWidget(self.fuzzingAreaLabel)
        self.widget = QtWidgets.QWidget(self.fuzzingAreaPanel)
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_12.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.fuzzingAreaPanel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_10)

        self.retranslateUi(pcapView)
        self.packetDisplay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pcapView)

    def retranslateUi(self, pcapView):
        _translate = QtCore.QCoreApplication.translate
        pcapView.setWindowTitle(_translate("pcapView", "PCAP View"))
        self.pcapFileLabel.setText(_translate("pcapView", "PCAP File"))
        self.pcapFileLabel2.setText(_translate("pcapView", "PCAP File"))
        self.pcapFilePath.setText(_translate("pcapView", "PCAP File Path"))
        self.pcapOpenButton.setText(_translate("pcapView", "Open"))
        self.pcapCancelButton.setText(_translate("pcapView", "Cancel"))
        self.capFilterLabel.setText(_translate("pcapView", "Capture Filter"))
        self.capFilterLabel2.setText(_translate("pcapView", "Filter"))
        self.capFilterExpr.setText(_translate("pcapView", "Filter Expression"))
        self.capFilterApply.setText(_translate("pcapView", "Apply"))
        self.capFilterClear.setText(_translate("pcapView", "Clear"))
        self.packetAreaLabel.setText(_translate("pcapView", "Packet Area"))
        self.dissectedList.headerItem().setText(0, _translate("pcapView", "packets"))
        __sortingEnabled = self.dissectedList.isSortingEnabled()
        self.dissectedList.setSortingEnabled(False)
        self.dissectedList.topLevelItem(0).setText(0, _translate("pcapView", "Frame 718: frame, eth , ip, tcp"))
        self.dissectedList.topLevelItem(0).child(0).setText(0, _translate("pcapView", "Frame...."))
        self.dissectedList.topLevelItem(0).child(1).setText(0, _translate("pcapView", "Ethernet..."))
        self.dissectedList.topLevelItem(0).child(2).setText(0, _translate("pcapView", "Internet..."))
        self.dissectedList.topLevelItem(0).child(3).setText(0, _translate("pcapView", "Transmission"))
        self.dissectedList.topLevelItem(1).setText(0, _translate("pcapView", "Frame..."))
        self.dissectedList.topLevelItem(2).setText(0, _translate("pcapView", "Frame....."))
        self.dissectedList.topLevelItem(3).setText(0, _translate("pcapView", "Frame......."))
        self.dissectedList.setSortingEnabled(__sortingEnabled)
        self.packetDisplay.setTabText(self.packetDisplay.indexOf(self.dissectedTab), _translate("pcapView", "Dissected"))
        self.binaryList.headerItem().setText(0, _translate("pcapView", "packets"))
        self.packetDisplay.setTabText(self.packetDisplay.indexOf(self.binaryTab), _translate("pcapView", "Binary"))
        self.packetDisplay.setTabText(self.packetDisplay.indexOf(self.hexTab), _translate("pcapView", "HEX"))
        self.packetClearButton.setText(_translate("pcapView", "Clear"))
        self.fieldAreaLabel.setText(_translate("pcapView", "Field Area"))
        self.fieldAttList.headerItem().setText(0, _translate("pcapView", "Field name"))
        self.fieldAttList.headerItem().setText(1, _translate("pcapView", "Value"))
        self.fieldAttList.headerItem().setText(2, _translate("pcapView", "Mask"))
        self.fieldAttList.headerItem().setText(3, _translate("pcapView", "Display Format"))
        __sortingEnabled = self.fieldAttList.isSortingEnabled()
        self.fieldAttList.setSortingEnabled(False)
        self.fieldAttList.topLevelItem(0).setText(0, _translate("pcapView", "icmp type"))
        self.fieldAttList.topLevelItem(0).setText(1, _translate("pcapView", "08"))
        self.fieldAttList.topLevelItem(0).setText(2, _translate("pcapView", "0"))
        self.fieldAttList.topLevelItem(0).setText(3, _translate("pcapView", "Format"))
        self.fieldAttList.topLevelItem(1).setText(0, _translate("pcapView", "icmp code"))
        self.fieldAttList.topLevelItem(1).setText(1, _translate("pcapView", "00"))
        self.fieldAttList.topLevelItem(1).setText(2, _translate("pcapView", "0"))
        self.fieldAttList.topLevelItem(1).setText(3, _translate("pcapView", "Format"))
        self.fieldAttList.topLevelItem(2).setText(0, _translate("pcapView", "icmp checksum"))
        self.fieldAttList.topLevelItem(2).setText(1, _translate("pcapView", "6861"))
        self.fieldAttList.topLevelItem(2).setText(2, _translate("pcapView", "1"))
        self.fieldAttList.topLevelItem(2).setText(3, _translate("pcapView", "Format"))
        self.fieldAttList.topLevelItem(3).setText(0, _translate("pcapView", "iicmp dent"))
        self.fieldAttList.topLevelItem(3).setText(1, _translate("pcapView", "809e"))
        self.fieldAttList.topLevelItem(3).setText(2, _translate("pcapView", "0"))
        self.fieldAttList.topLevelItem(3).setText(3, _translate("pcapView", "Format"))
        self.fieldAttList.topLevelItem(4).setText(0, _translate("pcapView", "icmp seq"))
        self.fieldAttList.topLevelItem(4).setText(1, _translate("pcapView", "0f00"))
        self.fieldAttList.topLevelItem(4).setText(2, _translate("pcapView", "2"))
        self.fieldAttList.topLevelItem(4).setText(3, _translate("pcapView", "Format"))
        self.fieldAttList.setSortingEnabled(__sortingEnabled)
        self.packetSaveButton.setText(_translate("pcapView", "Save Modification"))
        self.forwardButton.setText(_translate("pcapView", "Forward"))
        self.dropButton.setText(_translate("pcapView", "Drop"))
        self.addToFuzzButton.setText(_translate("pcapView", "+"))
        self.removeFromFuzzButton.setText(_translate("pcapView", "-"))
        self.fuzzingAreaLabel.setText(_translate("pcapView", "Fuzzing Area"))
        self.label_7.setText(_translate("pcapView", "Selected Packet Name"))
        self.lineEdit.setText(_translate("pcapView", "Selected packet name"))
        self.label_6.setText(_translate("pcapView", "Selected Field Name"))
        self.lineEdit_2.setText(_translate("pcapView", "Selected field name"))
        self.label_5.setText(_translate("pcapView", "Expected Return Type"))
        self.lineEdit_3.setText(_translate("pcapView", "Return type"))
        self.label_3.setText(_translate("pcapView", "Minimum"))
        self.lineEdit_5.setText(_translate("pcapView", "Minimum"))
        self.label_4.setText(_translate("pcapView", "Maximum"))
        self.lineEdit_4.setText(_translate("pcapView", "Maximum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pcapView = QtWidgets.QWidget()
    ui = Ui_pcapView()
    ui.setupUi(pcapView)
    pcapView.show()
    sys.exit(app.exec_())

